# Generated by Django 5.2.6 on 2025-09-05 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='value',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receipt',
            name='value',
            field=models.FloatField(default=15),
            preserve_default=False,
        ),
    ]
