# Generated by Django 5.2.6 on 2025-09-05 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_invoice_value_receipt_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('category', models.IntegerField()),
                ('value', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='category',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='title',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='value',
        ),
        migrations.AddField(
            model_name='invoice',
            name='expense',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
