# Generated by Django 5.2.6 on 2025-09-08 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_expense_user_delete_expenses_alter_receipt_invoice_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
