# Generated by Django 5.2.6 on 2025-09-16 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_expense_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='value',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='expense',
            name='value',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='value',
            field=models.FloatField(default=0),
        ),
    ]
