# Generated by Django 5.2.6 on 2025-09-21 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_document_alter_category_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('priority_value', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Priorities',
                'ordering': ['priority_value', 'title'],
            },
        ),
        migrations.RenameIndex(
            model_name='category',
            new_name='api_categor_priorit_04985f_idx',
            old_name='api_categor_priorit_0dc0de_idx',
        ),
        migrations.AddIndex(
            model_name='priority',
            index=models.Index(fields=['priority_value'], name='api_priorit_priorit_6eb7aa_idx'),
        ),
        migrations.AddIndex(
            model_name='priority',
            index=models.Index(fields=['title'], name='api_priorit_title_46a762_idx'),
        ),
        migrations.AlterField(
            model_name='category',
            name='priority',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='api.priority'),
        ),
    ]
