# Generated by Django 5.2.6 on 2025-09-22 18:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_priority_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='expense',
            name='api_expense_value_6ef019_idx',
        ),
        migrations.RemoveIndex(
            model_name='invoice',
            name='api_invoice_expense_c0fd4f_idx',
        ),
        migrations.RemoveIndex(
            model_name='invoice',
            name='api_invoice_value_674194_idx',
        ),
        migrations.RemoveIndex(
            model_name='receipt',
            name='api_receipt_value_222207_idx',
        ),
        migrations.RenameField(
            model_name='expense',
            old_name='value',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='value',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='receipt',
            old_name='value',
            new_name='amount',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='expense',
        ),
        migrations.AddField(
            model_name='expense',
            name='invoice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='api.invoice'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='api.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='title',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receipt',
            name='expense',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='api.expense'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='receipt',
            name='invoice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='api.invoice'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['amount'], name='api_expense_amount_be7531_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['amount'], name='api_invoice_amount_a4d5a9_idx'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['amount'], name='api_receipt_amount_ab4e92_idx'),
        ),
    ]
