# Generated by Django 5.2.6 on 2025-09-22 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_expense_api_expense_value_6ef019_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='expense_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
