# Generated by Django 5.2.6 on 2025-09-23 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_expense_expense_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='expense',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='api.expense'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='invoice',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='api.invoice'),
        ),
    ]
